# Introdução {#sec-introducao}

## Premissas

Esse livro pretende estudar os fenômenos de ouvir vozes, ter visões e sentir a presença de uma entidade de um ponto de vista da interpretação individual e social desses fenômenos ao longo da história. A tese central é que, apesar de cada época apresentar uma narrativa socialmente predominante, esses fenômenos sempre foram interpretados de formas diversas pelos indivíduos de cada época. A ideia é que não há uma evoluçõa linear da forma como as sociedades interpretam esses fenômenos, mas que apesar de cada época apresentar uma narrativa mais socialmente aceita, do ponto de vista individual sempre houve e continua existindo uma variedade grande de interpretações. Além disso, uma outra hitpótese é que quando a interpretação individual está em desacordo com a interpretação ou narrativa mais aceita, os indivíduos geralmente evitam discutir ou revelar suas próprias formas de interpretar suas vivências.

Para analisar esses teses esse livro se divide em partes

A primera parte introduz a posição filosófica da busca por um sentido, a busca pelos significados das experiências vividas, para então focar na busca pelo significado dessas vivências em especial.

A segunda parte analisa como essas experiências fizeram e fazem parte dos elementos sagrados de diversas culturas, analisando como vozes, visões e os relatos de sentir uma presença estão presentes em diversas religiões, fazendo parte intrínseca da construção dessas instituições.

A terceira parte  analisa essas experiências na esfera mundana, no cotidiano da vida, em diversas situações fora do contexto religioso. 

A quarta parte analise esses fenômenos do ponto de vista da ciência e da medicina.

A quinta parte tenta concluir a análise.

