# Vozes, visões e o Discretio Spiritum {#sec-discretio-spiritum}

Durante o período monástico medieval, por volta dos séculos XII e XIII, visões eram consideradas um sinal da santidade, especialmente para mulheres [@beckman2012mysticism, p. 183]. As mulheres carismáticas eram, aos olhos da comunidade dessa época, um ponto de encontro entre o espiritual e o mundano, onde os mortos e os vivos podiam se encontrar.

Cidadãos comuns, autoridades seculares e religiosas, consultavam mulheres visionárias para acessar informações de todos os tipos: o paradeiro das almas dos falecidos, a visão de Deus sobre questões políticas e eclesiais e o verdadeiro significado espiritual de passagens bíblicas [@beckman2012mysticism, p. 184].

## A expansão e o controle das visões

Ao final do século XIII, o fenômeno de mulheres visionárias se espalhou pela Europa. Entretanto, apesar da crença no acesso direto ao divino ser um princípio central do cristianismo e um poderoso estímulo à fé, é também, ao mesmo tempo, uma séria ameaça às autoridades eclesiásticas, pois aqueles que afirmam ter experimentado o contato intenso e não mediado com Deus pode ser levado a questionar os paradigmas e controles religiosos tradicionais.

Consequentemente, as religiões institucionais têm sido historicamente desconfiadas daqueles que reivindicam novas revelações \[voaden1994gods\].

## O sistema de controle eclesiástico

Como resultado, as religiões organizadas muitas vezes desenvolveram maneiras de controlar os que tendem a confiar mais em sua própria experiência transcendental do que na autoridade religiosa estabelecida.

Na Igreja Católica, com sua longa tradição e vida institucional altamente desenvolvida, foi desenvolvido um elaborado sistema para controlar e canalizar visionários, um sistema projetado para conter suas revelações dentro das estruturas aprovadas dos ensinamentos prescritos e dogmas institucionais da Igreja.

::: callout-important
## Discretio Spirituum

Esse sistema está incorporado na doutrina do *discretio spirituum*, um protocolo para tentar distinguir as verdadeiras visões (manifestações divinas) das falsas visões (manifestações diabólicas) \[voaden1994gods\].
:::

O *discretio spiritum* não pretende demonstrar se as visões ocorreram ou não, mas sim declarar a **origem** da visão, se era divina ou não. No final da era medieval, entendia-se que a capacidade de diferenciar essas visões era trabalho de *experts*, era um conhecimento que se adquiria através do estudo.