# Ouvi uma voz, então, alguém disse algo {#sec-ouvi-uma-voz}

O som da linguagem falada, uma voz, não é um som aleatório. A existência de uma voz implica na presença de alguém que fala, de um ser consciente e com intencionalidade. A experiência de ouvir uma voz pode indicar ao sujeito que a escuta a presença de um outro ser, ou de uma entidade. Se por um lado podemos nos perguntar se esse fenômeno é um sintoma de uma doença, muitas vezes a questão para o sujeito que vive a experiência é outra: de quem é a voz que ele escuta?

Ouvir uma voz na ausência de um falante visível gera uma questão importante para a humanidade: **quem é o autor da voz?** A resposta a essa pergunta tem sido debatida há milênios. Aqueles que escutam vozes que outros não conseguem escutar já foram considerados místicos ou profetas, já foram beatificados ou crucificados e, mais recentemente, considerados potenciais pacientes.

## A perspectiva do ouvidor

O sujeito que vivencia essa experiência tem sua própria interpretação acerca de quem é o autor da voz. Num recente estudo com 153 ouvidores de vozes:

-   **22%** disseram que as vozes eram de uma pessoa conhecida
-   **16%** consideravam que as vozes eram de entidades espirituais

Num outro estudo, a maioria dos pacientes atribuía as vozes a espíritos benevolentes [@sommer2010healthy].

::: callout-tip
## Experiência religiosa

Muitas vezes a voz é interpretada como sendo de Deus, sendo uma das mais intensas e íntimas experiências de religiosidade [@dein2015god].
:::

## Interpretações divergentes

Uma questão frequentemente conflituosa é que nem sempre a interpretação do próprio sujeito que escuta uma voz é compartilhada pelos outros. Assim, é possível que amigos, familiares, profissionais, médicos e teólogos tenham suas próprias interpretações acerca do fenômeno vivenciado por alguma pessoa.