# Vozes, visões e religiosidade {#sec-vozes-religiosidade}

Muito antes da criação do termo alucinação e de sua e introdução no campo médico, os fenômenos de visões e vozes já faziam parte da história da humanidade desde tempos remotos, estando presentes em todas as culturas, sempre carregando significados culturalmente importantes [@jardri2013neuroscience].

Historicamente essas vivências eram consideradas importantes formas de comunicação com divindades e outras entidades espirituais boas ou más. A partir do século XIX, ao lado dessas interpretações religiosas, as vozes começaram também a ser interpretadas como sinal de uma possível patologia mental.

## A complexidade contemporânea

Vivemos numa época complexa, com uma grande diversidade de interpretações desse fenômeno, envolvendo religião, cultura e ciência de uma forma indissociável. Diversas teorias diferentes e muitas vezes contraditórias tentam explicar as causas dessas vozes e dessas visões.

Entretanto, se por um lado tentar descobrir as causas desses fenômenos pode ser uma busca cheia de conflitos e dificuldades, por outro lado, buscar compreender como cada sujeito e como cada cultura interpreta esse fenômeno é extremamente importante.

::: callout-note
## O significado pessoal e cultural

Independente das explicações causais, a interpretação pessoal e cultural do significado das vozes e de visões é parte integrante da experiência desse fenômeno, podendo muitas vezes fazer com que esse fenômeno seja sentido de forma positiva ou negativa por quem o vivencia.
:::

## Espiritualidade como contexto

Espiritualidade e religiosidade são contextos significativos nos quais as vozes podem ser experimentadas e interpretadas, fornecendo importantes quadros de referências para dar significado a tais experiências.

Muitas vezes as vozes são interpretadas como uma parte importante de uma experiência espiritual que pode ser afirmada por sua comunidade religiosa, muitas vezes construindo significados para uma toda comunidade e, às vezes, para toda a humanidade.

Em épocas anteriores, essas experiências eram culturalmente integradas, carregadas de significado e acreditava-se que seu conteúdo continha uma mensagem para o indivíduo ou o mundo [@berrios1996history, p. 35].