# Vozes, visões, revelações e o nascimento das religiões {#sec-vozes-revelacoes}

As experiências de ouvir e ver algo que os outros não conseguem perceber são, desde a antiguidade, interpretadas como formas de comunicação com deuses, com entidades espirituais (imateriais) ou com os mortos [@laroi2014culture]. Durante a maior parte da história da humanidade, esses fenômenos eram entendidos e conceituados como diversos fenômenos diferentes, descritos sob variados termos tais como visões, aparições, fantasmas, fantasias, imaginações, contemplações, ideias sobrenaturais etc.

Além dos diferentes nomes, esses fenômenos eram frequentemente interpretadas como oportunidades de conectar o mundo real com o mundo espiritual, como revelações divinas, serviam para predizer o futuro, serviam como diretivas do que fazer e que do que não fazer, serviam como mensagens a um sujeito ou a um povo e, inúmeras vezes na história, "vozes" serviram como chamamento a uma ação.

## Moisés e a sarça ardente

As tradições religiosas judaicas, cristãs, muçulmanas e mórmons todas consideram que Deus fala com a humanidade e revela suas verdades [@stark1999revelations]. Um dos acontecimentos históricos mais importantes do ocidente é relato bíblico de Moisés ter ouvido uma voz que disse:

> "Eu sou o Deus de seu pai, o Deus de Abraão, o Deus de Isaque, o Deus de Jacó"

E que então o nomeou para libertar seu povo do Egito em direção à Terra Prometida (Êxodo 3:1-22) [@robinson1997moses]. Ainda segundo o relato bíblico, três meses depois de terem saído do Egito os israelitas chegaram ao Monte Sinai, onde novamente uma voz fala a Moisés e revela a ele os mandamentos que seu povo deveria seguir (Êxodo 20:1-17).

## As visões de Ezequiel

Séculos mais tarde, durante o exílio dos judeus do reino de Judá para a Babilônia, as visões do profeta Ezequiel ajudaram a manter a esperança no futuro e a criar a identidade do povo Judeu [@isbouts2019ezekiel]. Em suas visões Ezequiel viu (previu) a restauração da glória do povo Judeu, viu em detalhes o futuro templo Judeu.

As visões emocionantes de Ezequiel (Ezequiel 1:1-28), convenceram o povo Judeu que a aliança com Deus não havia sido quebrada e que, no devido tempo, Deus conduziria seu povo de volta a Israel [@isbouts2019ezekiel].

## O surgimento do islamismo

O islamismo também surgiu de eventos relacionados à uma voz que falava a um escolhido. De acordo com a tradição islâmica, numa noite, durante o mês do Ramadã, no ano 610 dC, enquanto Maomé meditava em uma caverna no monte Hira, nos arredores da cidade de Meca, teve a visão do anjo Gabriel que o declarou profeta de Deus.

Os eventos daquela noite provariam ser um ponto de virada não apenas para Maomé, mas também para a história religiosa. O encontro foi o primeiro de uma série de experiências que durariam até sua morte, 22 anos depois. As mensagens recebidas por Maomé ao longo dos anos foram coletadas em um único volume, constituindo o Alcorão, texto sagrado do Islã [@gwynne2018religions].

## A conversão de Saulo/Paulo

Visões e vozes também fizeram parte da construção do cristianismo. Saulo de Tarso, cidadão Judeu e Romano, perseguidor das primeiras comunidades cristãs, se converteu ao cristianismo depois de ouvir uma voz que dizia:

> "Saulo, Saulo, porque me persegues?" (Atos 9:1-6)

A partir daí, conhecido pelo nome de Paulo, tornou-se um dos líderes da primeira geração de cristãos, sendo considerado a pessoa mais importante na história do cristianismo depois de Jesus [@harrer1940saul; @manchester1972blindness].