# Vozes, visões e seus efeitos nas guerras {#sec-vozes-guerras}

No final do período medieval, as vozes escutadas por uma jovem de 13 anos de idade tiveram um profundo impacto no rei francês, Carlos VII, levantaram as esperanças dos franceses, definiram o rumo da guerra com a Inglaterra e mudaram o curso da história.

## O contexto da Guerra dos Cem Anos

Durante o período de 1337 a 1453, França e Inglaterra travaram uma série de conflitos conhecidos como a Guerra dos Cem Anos. No quarto período dessa guerra, com a morte de Carlos VI e Henrique V, os reinos da França e Inglaterra foram herdados por Henrique VI, na época uma criança recém-nascida.

Mas na França estava dividida entre os que apoiavam a Inglaterra e os que apoiavam Carlos VII, que acabou sendo também coroado rei francês em 1422. A França estava devastada pela guerra com a Inglaterra e pela própria cisão interna. Mas uma profecia alegava que a França seria restaurada por uma virgem [@ireland1883joan].

## A história de Joana D'Arc

Joana D'Arc, uma jovem francesa, começou a ouvir vozes e ter visões aos 13 anos de idade que identificou como as faces de santos e anjos, que a encorajavam a seguir uma vida piedosa, e a libertar a cidade de Orleans do cerco dos ingleses [@nicastro2016joan].

Por volta de 1429 Joana conseguiu uma audiência com o Carlos VII na qual alegava ter sido enviada por Deus para libertar a França [@constant2016concepts, p. 226]. Por três semanas Joana foi avaliada por juristas e teólogos sobre suas virtudes e sua fé. A comissão então concluiu não haver sinais de maldade em Joana, apenas humildade, bondade, piedade, simplicidade e virgindade, tendo recomendado então que fossem dadas armas a Joana e que ela se juntasse ao exército em Orleans [@constant2016concepts, p. 231-32].

## O impacto militar

Os franceses estavam tentando há 8 meses recuperar Orleans sem sucesso, mas a chegada de Joana inspirou as tropas e reascendeu os ânimos. Os franceses saem vitoriosos dessa batalha e a presença de Joana foi creditada como fundamental.

De abril a julho de 1429 os franceses obtiveram uma série de vitórias que culminaram com a coroação de Carlos VII. Essas vitórias serviram para aumentar a crença de que Joana havia sido realmente enviada por Deus [@constant2016concepts].

## Julgamento e legado

Em 1430 Joana foi capturada pelos ingleses, levada a julgamento e queimada na fogueira como herege [@vale1974charles]. A caracterização de Joana como bruxa tinha propósitos políticos, pois buscava invalidar a posse de Carlos VII como rei da França.

Após a guerra o Papa Calisto III abriu um novo processo de revisão que concluiu, em 1456, que Joana era inocente das acusações. Ao longo de vários séculos a figura de Joana e suas vozes e visões foram discutidas, até que foi beatificada em 1909 e canonizada em 1920. Sua história já serviu para inúmeros livros, filmes e até mesmo jogos de computadores.