# As dimensões da experiência de ouvir vozes {#sec-dimensoes-experiencia}

A compreensão plena desse fenômeno não se limita à descrição do que foi visto ou ouvido. É necessário avaliar o contexto em que tais fenômenos ocorrem, a interpretação dada ao fenômeno pelo próprio indivíduo que o experimenta, o impacto em sua vida, o controle e a frequência e a duração dos fenômenos, o conteúdo emocional associado e diversos outros fatores relacionados. Apenas dessa forma é possível tentar compreender esses fenômenos em sua totalidade.

## Além da definição simples

O termo "alucinação auditiva verbal" significa a percepção de uma voz na ausência de um estímulo sensorial auditivo. Entretanto, a experiência de ouvir vozes envolve muito mais detalhes do que essa mera descrição. Vários autores entendem que a vivência de escutar vozes abarca uma série de dimensões que necessitam ser analisadas em conjunto. Por exemplo, frequentemente vozes e visões fazem parte de um mesmo fenômeno, quando alguém vê uma imagem com a qual mantém uma conversação.

## Variedade das experiências

Vários estudos mostraram que enquanto para alguns a experiência de ouvir vozes é como se realmente uma voz estivesse sendo falada, para outros é como se estivessem ouvindo seus próprios pensamentos [@karlsson2008reality; @woods2015experiences]:

-   Às vezes é apenas um som, um barulho ou uma palavra, outras vezes é uma conversação
-   Às vezes a voz conversa com o indivíduo, outras vezes as vozes conversam entre si
-   Às vezes parece vir do interior da cabeça, outras vezes do espaço externo ou até mesmo de um objeto

[@deleede2013comprehensive; @karlsson2008reality; @nayani1996auditory; @woods2015experiences]

## Modelos multidimensionais

Por um ponto de vista clínico, Chen e Berrios descreveram **11 dimensões** das alucinações [@chen1996recognition]:

1.  Insight
2.  Detalhamento
3.  Complexidade
4.  Localização espacial
5.  Intensidade
6.  Controle voluntário
7.  Constância (frequência)
8.  Bizarrice
9.  Situação
10. Atribuição
11. Conexão com delírios

Outros autores salientaram a importância das características emocionais, do impacto na vida, da frequência e da duração, da localização, do quão alta são as vozes, do controle voluntário e da interpretação atribuída ao fenômeno [@haddock1999scales].

## Características das vozes {#sec-caracteristicas-vozes}

Algumas características das vozes são consideradas tradicionalmente como mais sugestivas de transtornos mentais. Kurt Schneider considerava como sendo "sintomas de primeira ordem" (SPO) as experiências de:

-   Ouvir duas ou mais vozes discutindo entre si
-   Vozes comentando as ações dos pacientes
-   A experiência uma voz falando em voz alta os próprios pensamentos dos pacientes

Para Kurt Schneider esses eram alguns dos "sintomas de primeira ordem", indicando uma maior possibilidade do diagnóstico de esquizofrenia.

::: callout-warning
## Limitações diagnósticas

Muitos estudos que avaliaram a utilidade diagnóstica dos SPO chegaram a resultados inconclusivos a respeito da utilidade dos SPO [@malinowski2020schneider]. Uma revisão da Cochrane de 2015 concluiu que os SPO identificam corretamente pacientes com esquizofrenia em cerca de 75 a 95% das vezes e que cerca de até 20% dos pacientes sem esquizofrenia podem apresentar esses sintomas [@soaresweiser2015firstrank].
:::

## Controle voluntário {#sec-controle-voluntario}

Algumas pessoas que escutam vozes conseguem influenciar as vozes, ou seja, conseguem iniciar o fenômeno ou interrompê-lo de alguma forma:

-   Alguns conseguem iniciar o processo de ouvir uma voz através de um esforço de concentração [@nayani1996auditory]
-   Alguns conseguem interromper ou reduzir as vozes utilizando estratégias de distração ou lidando com as vozes de alguma forma [@deleede2013comprehensive]

## Frequência e duração {#sec-frequencia-duracao}

A frequência com que o fenômeno de ouvir vozes acontece é bastante variável [@deleede2013comprehensive]:

-   Pode ter sido uma única experiência
-   Pode ocorrer de vez em quando ou com frequência regular
-   Às vezes diariamente
-   Às vezes de forma persistente a todo momento

Quando ocorre, a voz pode falar por alguns minutos apenas, por horas a fio ou até mesmo de forma constante [@deleede2013comprehensive].

## Conteúdo emocional {#sec-conteudo-emocional}

O conteúdo emocional pode tanto ser neutro, como positivo ou negativo [@nayani1996auditory]:

| Contexto                             | Conteúdo mais comum               |
|--------------------------------------|-----------------------------------|
| Pacientes com quadros psiquiátricos  | Negativo, acusador ou estressante |
| Ouvidores sem patologia psiquiátrica | Neutro ou positivo                |

::: callout-important
## Diferença crucial

De fato, o conteúdo emocional das vozes foi o fator que mais diferenciou ouvidores de vozes com e sem transtornos psiquiátricos [@deleede2013comprehensive; @honig1998auditory].
:::

## Impacto na vida {#sec-impacto-vida}

Alguns sentem que as vozes atrapalham a vida, enquanto outros relatam que as vozes proporcionaram uma melhora na qualidade de vida e nos relacionamentos [@woods2015experiences].

Naqueles com menor controle das vozes ou que vivenciam vozes com conteúdo acusador ou agressivo referem níveis mais altos de estresse e prejuízo na vida [@nayani1996auditory].

## Interpretação atribuída {#sec-interpretacao-atribuida}

Uma importante dimensão da experiência de ouvir vozes diz respeito à interpretação atribuída ao fenômeno pela própria pessoa que o vivencia.

Esse é um dos aspectos mais controversos do fenômeno, pois a interpretação atribuída pelo próprio sujeito pode carregar importantes significados pessoais e pode ou não estar em conformidade com a interpretação de sua comunidade. Além disso, pode também haver dissonância entre a interpretação pessoal e a interpretação clínica do fenômeno.

As crenças pessoais de cada um certamente influenciam a interpretação dada ao fenômeno:

-   Diversas religiões têm entre suas premissas a possibilidade da comunicação entre Deus e o ser humano, ou entre espíritos ou divindades e o ser humano, ratificando culturalmente essa interpretação sobre o fenômeno de ouvir vozes

-   Por outro lado, alterações bioquímicas no cérebro também podem ser responsáveis pelo fenômeno de ouvir vozes, seja através do uso de substâncias alucinógenas ou patologias cerebrais